#!/usr/bin/env node
// Writes every static AI surface into public/ before the Next build:
//
//   public/ai.md  public/ai.txt  public/ai.json   the /ai document as data
//   public/llms.txt                               short install block
//   public/units/<id>/prompt.md                   one unit's full prompt
//   public/files/<Name>.swift                     verbatim copies of ../units
//
// The prose and the templates are NOT duplicated here: this script imports
// src/lib/aiPage.ts and src/lib/prompts.ts, the same modules the /ai route and
// the site use, plus the repository links in src/lib/site.ts. Node loads them
// by stripping types, which needs Node >= 22.6 (on by default from 23.6). All
// three are pure and type-import-only for exactly that reason.
//
// Source of truth is ../units, read the way src/lib/units.ts reads it.
//
// `--sync <dir>` additionally mirrors the generated files into an export
// directory. `next build` writes a React flight payload to out/<route>.txt,
// which lands on top of the public/ai.txt this script wrote, so the postbuild
// pass restores it. Nothing in <dir> is deleted.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  aiInvariants,
  aiMarkdown,
  aiRecord,
  aiText,
  buildAiDoc,
} from "../src/lib/aiPage.ts";
import { buildLibraryPrompt, buildUnitPrompt } from "../src/lib/prompts.ts";
import * as site from "../src/lib/site.ts";

const WEB_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const REPO_ROOT = path.resolve(WEB_ROOT, "..");
const UNITS_DIR = path.join(REPO_ROOT, "units");
const README = path.join(REPO_ROOT, "README.md");
const PUBLIC_DIR = path.join(WEB_ROOT, "public");

const HEADER = "# generated by scripts/gen-ai.mjs";

const syncIndex = process.argv.indexOf("--sync");
const SYNC_DIR =
  syncIndex === -1 ? null : path.resolve(WEB_ROOT, process.argv[syncIndex + 1]);

const read = (file) => fs.readFileSync(file, "utf8");

/** The first ```swift fence in README.md — the canonical usage lines. */
function readUsageBlock() {
  const match = read(README).match(/```swift\n([\s\S]*?)```/);
  return match ? match[1].trimEnd() : "";
}

/** "WowPressStyle / .wowPress()" -> ["WowPressStyle", "wowPress"] */
function entrySymbols(entry) {
  return entry
    .split("/")
    .map((s) => s.trim().replace(/^\./, "").split("(")[0].trim())
    .filter(Boolean);
}

function usageFor(manifest, usageBlock) {
  const symbols = entrySymbols(manifest.platforms.swiftui.entry).map((s) =>
    s.toLowerCase(),
  );
  const lines = usageBlock
    .split("\n")
    .filter((line) => symbols.some((s) => line.toLowerCase().includes(s)));
  return lines.length > 0 ? lines.join("\n") : manifest.platforms.swiftui.entry;
}

/** Same check as src/lib/units.ts: [{ state, motion, haptic }] or left out, with a warning. */
function checkStates(id, raw) {
  if (raw === undefined) return undefined;
  const ok =
    Array.isArray(raw) &&
    raw.every(
      (row) =>
        typeof row?.state === "string" &&
        typeof row?.motion === "string" &&
        typeof row?.haptic === "string",
    );
  if (ok) return raw;
  console.warn(
    `gen-ai: "${id}" unit.json \`states\` is not [{ state, motion, haptic }]; left out until it is`,
  );
  return undefined;
}

function loadCatalog() {
  const index = JSON.parse(read(path.join(UNITS_DIR, "index.json")));
  const usageBlock = readUsageBlock();

  const core = {
    path: index.core,
    fileName: path.basename(index.core),
    source: read(path.join(UNITS_DIR, index.core)),
  };

  // Same rule as src/lib/units.ts: a listed unit whose unit.json or Swift file has not
  // landed yet is skipped with a warning, so the index can be updated first.
  const units = index.units.flatMap((id) => {
    const manifestFile = path.join(UNITS_DIR, id, "unit.json");
    if (!fs.existsSync(manifestFile)) {
      console.warn(`gen-ai: skipping "${id}" (listed in units/index.json): no unit.json yet`);
      return [];
    }
    const manifest = JSON.parse(read(manifestFile));
    const swiftFile = path.join(UNITS_DIR, id, manifest.platforms.swiftui.file);
    if (!fs.existsSync(swiftFile)) {
      console.warn(
        `gen-ai: skipping "${id}" (listed in units/index.json): no ${manifest.platforms.swiftui.file} yet`,
      );
      return [];
    }
    return [
      {
        ...manifest,
        states: checkStates(id, manifest.states),
        source: read(swiftFile),
        usage: usageFor(manifest, usageBlock),
        mediaSrc: `/media/${manifest.id}.mp4`,
      },
    ];
  });

  return { version: index.version, core, units, usageBlock };
}

const written = [];

function write(file, body) {
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, body, "utf8");
  written.push(path.relative(WEB_ROOT, file));
}

/** Prompt documents carry a provenance line; the /ai documents do not, so a
 *  person copying /ai.md pastes only the description. */
const withHeader = (body) => `${HEADER}\n\n${body}`;

function copyRaw(from, to) {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
  written.push(path.relative(WEB_ROOT, to));
}

const catalog = loadCatalog();
const doc = buildAiDoc(catalog, site);
const markdown = aiMarkdown(doc);
const text = aiText(doc);
const record = aiRecord(catalog, site);
const json = `${JSON.stringify(record, null, 2)}\n`;

// One rendering must not lose a fact another one keeps. Among them: the
// free-and-open sentence, the three GitHub links and the MIT license.
const serialized = { "ai.md": markdown, "ai.txt": text, "ai.json": json };
for (const fact of aiInvariants(catalog, site)) {
  for (const [name, body] of Object.entries(serialized)) {
    if (!body.includes(fact)) {
      throw new Error(`gen-ai: ${name} is missing a required fact: ${fact}`);
    }
  }
}

// These two trees are generated in full, so a removed unit cannot leave a
// stale file behind. Nothing else under public/ is touched.
for (const dir of ["units", "files"]) {
  fs.rmSync(path.join(PUBLIC_DIR, dir), { recursive: true, force: true });
}

write(path.join(PUBLIC_DIR, "ai.md"), markdown);
write(path.join(PUBLIC_DIR, "ai.txt"), text);
write(path.join(PUBLIC_DIR, "ai.json"), json);
write(
  path.join(PUBLIC_DIR, "llms.txt"),
  withHeader(buildLibraryPrompt(catalog)),
);

copyRaw(
  path.join(UNITS_DIR, catalog.core.path),
  path.join(PUBLIC_DIR, "files", catalog.core.fileName),
);

for (const unit of catalog.units) {
  const file = unit.platforms.swiftui.file;
  write(
    path.join(PUBLIC_DIR, "units", unit.id, "prompt.md"),
    withHeader(buildUnitPrompt(unit, catalog.core)),
  );
  copyRaw(
    path.join(UNITS_DIR, unit.id, file),
    path.join(PUBLIC_DIR, "files", file),
  );
}

if (SYNC_DIR) {
  for (const rel of written) {
    const to = path.join(SYNC_DIR, path.relative("public", rel));
    fs.mkdirSync(path.dirname(to), { recursive: true });
    fs.copyFileSync(path.join(WEB_ROOT, rel), to);
  }
}

console.log(
  `gen-ai: ${written.length} files${SYNC_DIR ? ` (mirrored into ${path.relative(WEB_ROOT, SYNC_DIR)}/)` : ""}\n  ${written.join("\n  ")}`,
);
